#2. Write a game where you guess a number randomly generated by the computer

#generate random number
num <- sample(1:100,1)

#create placeholder vector to store user input 
guess <- -1

#prompt user input 
cat("I'm thinking of a number 1-100...")

#for loop to determine what output to give based on user input 
#for loop will run 10 times or it will stop when correct answer input due to break
for(i in 1:10){
  guess <- as.integer(x = readline(prompt="Enter an integer: "))
  if (guess == num){
    cat("Correct!")
    break
  }
  else if (guess < num){
    cat("Higher")
  }
  else if(guess > num){
    cat("Lower")
  }
}
